export default {
  GET_ALL_VALUES_FROM_STORAGE: 'GET_ALL_VALUES_FROM_STORAGE',
  GET_ALL_VALUES_FROM_STORAGE_SUCCESS: 'GET_ALL_VALUES_FROM_STORAGE_SUCCESS',
  GET_ALL_VALUES_FROM_STORAGE_FAILURE: 'GET_ALL_VALUES_FROM_STORAGE_FAILURE',

  SAVE_ALL_VALUES_IN_STORAGE: 'SAVE_ALL_VALUES_IN_STORAGE',
  SAVE_ALL_VALUES_IN_STORAGE_SUCCESS: 'SAVE_ALL_VALUES_IN_STORAGE_SUCCESS',
  SAVE_ALL_VALUES_IN_STORAGE_FAILURE: 'SAVE_ALL_VALUES_IN_STORAGE_FAILURE',

  REMOVE_ALL_VALUES_FROM_STORAGE: 'REMOVE_ALL_VALUES_FROM_STORAGE',
  REMOVE_ALL_VALUES_FROM_STORAGE_SUCCESS: 'REMOVE_ALL_VALUES_FROM_STORAGE_SUCCESS',
  REMOVE_ALL_VALUES_FROM_STORAGE_FAILURE: 'REMOVE_ALL_VALUES_FROM_STORAGE_FAILURE',
};
